# Generated by Django 4.1 on 2022-08-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=250)),
                ('Price', models.FloatField()),
                ('Stock', models.IntegerField()),
                ('Image', models.CharField(max_length=2500)),
            ],
        ),
    ]
